# Generated by Django 5.2 on 2025-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.TextField(default='No items'),
        ),
    ]
