# Generated by Django 5.2 on 2025-04-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_orderactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactionlog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to='base.order'),
        ),
    ]
