# Generated by Django 5.2 on 2025-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_productactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productactionlog',
            name='details',
            field=models.TextField(default='No details'),
            preserve_default=False,
        ),
    ]
