# Generated by Django 5.2 on 2025-04-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_productactionlog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='target_user',
        ),
    ]
